### ISSUE TITLE
[Tracking issue] When a resource limit is exceeded, it's clear what next steps should be taken

### ISSUE THREAD

**Issue by BigLep** [libp2p/go-libp2p-resource-manager#31]
When a resource limit is exceeded, we want to give go-libp2p consumers the the visibility, tools, and knowledge to debug issues on their own.  

This is a tracking issue for accomplishing this goal.  Specific items include:
- [ ] https://github.com/libp2p/go-libp2p-resource-manager/issues/25
- [ ] https://github.com/libp2p/go-libp2p-resource-manager/issues/26
- [ ] https://github.com/libp2p/go-libp2p-resource-manager/issues/27
- [ ] https://github.com/libp2p/go-libp2p-resource-manager/issues/28

**Comment by MarcoPolo** [comment]
I think this can be bundled with: https://github.com/libp2p/docs/issues/153 if so, I can take this.
